#! /bin/sh

set -e

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   exit 1
fi

echo "Copying MeshEditor.swf into Femhub..."
cp MeshEditor.swf $SPKG_LOCAL/share/onlinelab/core-home/static/external/
